<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <InvariantGlobalization>true</InvariantGlobalization>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1848</NoWarn>
    <Product>RealtimeTranslator</Product>
    <Version>0.0.0</Version>
    <InformationalVersion>$(Version)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <!-- テストプロジェクトから internal を見せる。 -->
  <ItemGroup Condition="'$(IsTestProject)' != 'true' AND $(MSBuildProjectName.StartsWith('RealtimeTranslator'))">
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
  </ItemGroup>

</Project>
