<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>RealtimeTranslator.Platform</RootNamespace>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealtimeTranslator.Core\RealtimeTranslator.Core.csproj" />
  </ItemGroup>

</Project>
